POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=atsd
DB_USER=atsd
DB_PASSWORD=atsd

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:atsd}?options=-c%20TimeZone=UTC
spring.datasource.username=${DB_USER:atsd}
spring.datasource.password=${DB_PASSWORD:atsd}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.open-in-view=false
