spring.datasource.url=jdbc:postgresql://localhost:5432/atsd?options=-c%20TimeZone=UTC
spring.datasource.username=atsd
spring.datasource.password=atsd
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
